import Lean.Compiler.JVM

/-!
Tests end-to-end execution of JVM bytecode generated by Lean.
Emits a classfile with an arithmetic method and a main method,
then executes it with `java` to verify JVM execution.
-/

open Lean.Compiler.JVM
open Lean.Compiler.JVM.Opcode

def main : IO Unit := do
  let mut cf : ClassFile := {
    className := "lean/test/ExecTest"
    superClass := "java/lang/Object"
  }

  -- Method: public static int computeAnswer() { return 20 + 22; }
  let mut computeCode := ByteArray.empty
  computeCode := Opcode.bipush 20 |>.emit computeCode
  computeCode := Opcode.bipush 22 |>.emit computeCode
  computeCode := Opcode.iadd |>.emit computeCode
  computeCode := Opcode.ireturn |>.emit computeCode

  let computeMethod : MethodDef := {
    accessFlags := ClassFile.ACC_PUBLIC ||| ClassFile.ACC_STATIC
    name := "computeAnswer"
    descriptor := "()I"
    maxStack := 4
    maxLocals := 0
    bytecodes := computeCode
  }
  cf := { cf with methods := cf.methods.push computeMethod }

  -- Register CP references for main method
  let (computeRef, cf') := cf.addMethodRef "lean/test/ExecTest" "computeAnswer" "()I"
  let (sysOutRef, cf') := cf'.addFieldRef "java/lang/System" "out" "Ljava/io/PrintStream;"
  let (printlnRef, cf') := cf'.addMethodRef "java/io/PrintStream" "println" "(I)V"
  cf := cf'

  -- Method: public static void main(String[] args)
  -- System.out.println(computeAnswer());
  let mut mainCode := ByteArray.empty
  mainCode := Opcode.getstatic sysOutRef |>.emit mainCode
  mainCode := Opcode.invokestatic computeRef |>.emit mainCode
  mainCode := Opcode.invokevirtual printlnRef |>.emit mainCode
  mainCode := Opcode.return_void |>.emit mainCode

  let mainMethod : MethodDef := {
    accessFlags := ClassFile.ACC_PUBLIC ||| ClassFile.ACC_STATIC
    name := "main"
    descriptor := "([Ljava/lang/String;)V"
    maxStack := 4
    maxLocals := 1
    bytecodes := mainCode
  }
  cf := { cf with methods := cf.methods.push mainMethod }

  let bytes := cf.toByteArray
  IO.FS.createDirAll "lean/test"
  IO.FS.writeBinFile "lean/test/ExecTest.class" bytes
  IO.println "ExecTest.class generated."
